version: "3"
services:
  superalgos:
    build: 
      context: ..
      dockerfile: ./Docker/Dockerfile
    image: ghcr.io/superalgos/superalgos:latest
    command: ["minMemo"]
    ports:
      - '34248:34248'
      - '18041:18041'
    volumes:
      - ../Data-Storage:/app/Data-Storage
      - ../Log-Files:/app/Log-Files
      - ../My-Workspaces:/app/My-Workspaces
    environment:
      PUID: '1000'
      PGID: '1000'
    restart: on-failure
